### ISSUE TITLE
Some question

### ISSUE THREAD

**Issue by kingda** [Javey/vdt.js#5]
Hello~I want to know this template engine to support what browser?Can it be used in  ie6 ?

**Comment by Javey** [comment]
Unfortunately, I don't test it in ie6. In my opinion, [virtual-dom](https://github.com/Matt-Esch/virtual-dom) which `vdt` based on doesn't support ie6, too. Because of some operations of dom.

**Comment by kingda** [comment]
Oh~I get it.Thank you~

**Comment by Javey** [comment]
Hi @kingda ，v1.0 has published and it support ie8. Would you like to have a try??
